sudo: required
dist: trusty

os:
  - linux
  - osx

language: cpp
cache: ccache

compiler:
  - gcc
  - clang

env:
  - TRAVIS_BUILD_TYPE=Debug TRAVIS_CMAKE_GENERATOR="Unix Makefiles"
  - TRAVIS_BUILD_TYPE=Release TRAVIS_CMAKE_GENERATOR="Unix Makefiles"
  - TRAVIS_BUILD_TYPE=Debug TRAVIS_CMAKE_GENERATOR="Xcode"
  - TRAVIS_BUILD_TYPE=Release TRAVIS_CMAKE_GENERATOR="Xcode"

matrix:
  exclude:
    - os: linux
      env: TRAVIS_BUILD_TYPE=Release TRAVIS_CMAKE_GENERATOR="Xcode"
    - os: linux
      env: TRAVIS_BUILD_TYPE=Debug TRAVIS_CMAKE_GENERATOR="Xcode"

install:
    - CI_DIR=$PWD
    - if [ "$TRAVIS_OS_NAME" = linux -o -z "$TRAVIS_OS_NAME" ]; then sudo sh -c 'echo "deb http://www.icub.org/ubuntu trusty contrib/science" > /etc/apt/sources.list.d/icub.list' ; fi
    - if [ "$TRAVIS_OS_NAME" = linux -o -z "$TRAVIS_OS_NAME" ]; then sudo apt-get update ; fi
    - if [ "$TRAVIS_OS_NAME" = linux -o -z "$TRAVIS_OS_NAME" ]; then sudo apt-get install -qq -y yarp --force-yes ; fi
    - if [ "$TRAVIS_OS_NAME" = linux -o -z "$TRAVIS_OS_NAME" ]; then sudo apt-get install -qq -y libeigen3-dev libboost-all-dev ; fi
    - if [ "$TRAVIS_OS_NAME" = osx -o -z "$TRAVIS_OS_NAME" ]; then gem install xcpretty; brew update  &> /dev/null; brew tap robotology/cask; brew tap homebrew/x11; brew tap homebrew/versions; brew tap robotology/science; brew install homebrew/versions/eigen32 tinyxml; brew install yarp; fi
    - git clone https://github.com/ocra-recipes/eigen_lgsm.git
    - cd eigen_lgsm ; mkdir build ; cd build ; cmake ..
    - sudo make install
    - cd $CI_DIR
    - git clone https://github.com/robotology-dependencies/qpOASES.git
    - cd qpOASES ; mkdir build ; cd build ; cmake ..
    - sudo make -j2 install
    - cd $CI_DIR
    - mkdir build ; cd build
    - mkdir ~/ocra-install
    - cmake .. -DCMAKE_INSTALL_PREFIX=~/ocra-install
script:
    - make -j2
    - make install
    #run tests
