sudo: required
dist: trusty

language: cpp

compiler:
  - gcc

install:
    - CI_DIR=$PWD
    - sudo sh -c 'echo "deb http://www.icub.org/ubuntu trusty contrib/science" > /etc/apt/sources.list.d/icub.list'
    - sudo apt-get update
    - sudo apt-get install -qq -y yarp --force-yes
    - sudo apt-get install -qq -y libeigen3-dev libboost-all-dev
    - git clone https://github.com/ocra-recipes/eigen_lgsm.git
    - cd eigen_lgsm ; mkdir build ; cd build ; cmake ..
    - sudo make install
    - cd $CI_DIR
    - mkdir build ; cd build
    - mkdir ~/ocra-install
    - cmake .. -DCMAKE_INSTALL_PREFIX=~/ocra-install
script:
    - make -j2
    - make install
    #run tests
