sudo: required
dist: trusty

language: cpp

compiler:
  - gcc

install:
    - sudo sh -c 'echo "deb http://www.icub.org/ubuntu trusty contrib/science" > /etc/apt/sources.list.d/icub.list'
    - sudo apt-get update
    - sudo apt-get install -qq -y yarp --force-yes
    - mkdir build ; cd build
    - mkdir ~/ocra-install
    - cmake .. -DCMAKE_INSTALL_PREFIX=~/ocra-install
script:
    - make -j2
    - make install
    #run tests
